import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Lightbulb, Sparkles } from 'lucide-react';
import { useEffect, useState } from 'react';
import { toast } from 'sonner';
import { SectionError } from '../components/domain/SectionError.js';
import { PageHeader } from '../components/layout/PageHeader.js';
import { Button } from '../components/primitives/Button.js';
import { Card } from '../components/primitives/Card.js';
import { CodeBlock } from '../components/primitives/CodeBlock.js';
import { EmptyState } from '../components/primitives/EmptyState.js';
import { PlanGate } from '../components/primitives/PlanGate.js';
import { Skeleton } from '../components/primitives/Skeleton.js';
import { Stat } from '../components/primitives/Stat.js';
import { api } from '../lib/api.js';
import { useAuth } from '../lib/auth.js';
import { absTime, monthLabel, usd } from '../lib/format.js';

/** ADR-009: verbatim, non-negotiable — must ride along with any downgradable-spend figure shown to the user. */
const METHODOLOGY_DISCLOSURE =
  "This estimate is generated by an offline analysis of your last 30 days of request data. It classifies requests by complexity and checks whether a less expensive model tier would have been appropriate. No requests are re-run or modified. Estimates are advisory only — actual savings depend on your application's quality requirements.";

// The analysis job writes this key into the summary jsonb, but its casing isn't contract-guaranteed
// (raw SQL passthrough, not a typed server response) — check both spellings defensively.
const ESTIMATED_SAVINGS_KEYS = ['estimated_savings_usd', 'estimatedSavingsUsd'];

const TRIGGER_TS_KEY = 'spillway_insights_trigger_ts';
const COOLDOWN_MS = 10 * 60 * 1000;

/** No server-side cooldown field exists — the 10-minute lock is purely a client-side localStorage timestamp. */
function cooldownRemainingMs(): number {
  const raw = localStorage.getItem(TRIGGER_TS_KEY);
  if (!raw) return 0;
  return Math.max(0, COOLDOWN_MS - (Date.now() - Number(raw)));
}

/** "estimated_savings_usd" → "Estimated savings usd"; camelCase keys get word-split first. */
function humanizeKey(key: string): string {
  return key
    .replace(/_/g, ' ')
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/^./, (c) => c.toUpperCase());
}

function formatSummaryValue(value: unknown): string {
  if (value === null || value === undefined) return '—';
  if (typeof value === 'number') return value.toLocaleString('en-US');
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (typeof value === 'string') return value;
  return JSON.stringify(value);
}

function findEstimatedSavings(
  summary: Record<string, unknown>,
): { key: string; usdValue: string | undefined } | null {
  for (const key of ESTIMATED_SAVINGS_KEYS) {
    if (key in summary) {
      const raw = summary[key];
      const usdValue = typeof raw === 'string' || typeof raw === 'number' ? String(raw) : undefined;
      return { key, usdValue };
    }
  }
  return null;
}

/**
 * Insights (bible §3.14): the "we found you money" surface — a weekly offline analysis of whether
 * cheaper model tiers would've served recent traffic. Reads are free (no entitlement check on the
 * GET per the reads-free doctrine) but the whole page sits behind PlanGate anyway — the entire point
 * of this screen is the gated write (trigger), so an ungated org should see the blurred preview +
 * upgrade CTA rather than a live button the server would just 402.
 */
export function InsightsPage() {
  const { session, activeOrgId } = useAuth();
  const queryClient = useQueryClient();
  const [, forceTick] = useState(0);

  const q = useQuery({
    queryKey: [activeOrgId, 'insights'],
    queryFn: api.getInsights,
    enabled: !!session && !!activeOrgId,
  });

  const trigger = useMutation({
    mutationFn: api.triggerInsights,
    onSuccess: () => {
      localStorage.setItem(TRIGGER_TS_KEY, String(Date.now()));
      toast.success('Analysis queued — results typically ready within a few minutes.');
      void queryClient.invalidateQueries({ queryKey: [activeOrgId, 'insights'] });
      forceTick((n) => n + 1);
    },
  });

  const cooldownActive = cooldownRemainingMs() > 0;

  // Re-render as the cooldown expires so the button re-enables itself without a manual refresh.
  useEffect(() => {
    if (!cooldownActive) return;
    const id = setInterval(() => forceTick((n) => n + 1), 15_000);
    return () => clearInterval(id);
  }, [cooldownActive]);

  const rawInsight = q.data?.insight ?? null;
  // A run that classified nothing (no request_features yet) isn't a report — showing
  // "$0.00 · 0 analyzed" reads as broken. Treat it as not-yet-analyzed.
  const insight =
    rawInsight && Number(rawInsight.summary?.['requests_analyzed'] ?? 1) === 0 ? null : rawInsight;
  const summary = insight?.summary ?? {};
  const est = insight ? findEstimatedSavings(summary) : null;
  // Engine-internal fields (method plumbing, spec-reference warnings) never reach the UI —
  // the methodology disclosure below is the user-facing framing.
  const INTERNAL_KEY = /warning|method|heuristic|seam/i;
  const restEntries = Object.entries(summary).filter(
    ([key]) => (!est || key !== est.key) && !INTERNAL_KEY.test(key),
  );
  const periodLabel = insight
    ? /^\d{4}-\d{2}$/.test(insight.period)
      ? monthLabel(insight.period)
      : insight.period
    : '';

  const runTrigger = (): void => trigger.mutate();

  return (
    <div>
      <PageHeader
        title="Insights"
        sub="Where Spillway finds spend you could have safely downgraded."
      />

      <PlanGate feature="chargeback" label="Savings insights">
        {q.isLoading ? (
          <div className="space-y-4">
            <Card>
              <Skeleton className="h-3 w-28" />
              <Skeleton className="mt-3 h-8 w-40" />
            </Card>
            <Card>
              <Skeleton className="h-3 w-32" />
              <Skeleton className="mt-3 h-4 w-full" />
              <Skeleton className="mt-2 h-4 w-2/3" />
            </Card>
          </div>
        ) : q.error ? (
          <SectionError error={q.error} onRetry={() => void q.refetch()} />
        ) : insight === null ? (
          <Card padding="none">
            <EmptyState
              icon={<Lightbulb size={20} aria-hidden />}
              headline="No savings analysis yet."
              body="Spillway runs a weekly analysis of your traffic to find safely-downgradable spend. Run it manually to get your first report."
              action={
                cooldownActive
                  ? undefined
                  : {
                      label: 'Run analysis now',
                      onClick: runTrigger,
                      testId: 'insights-trigger-btn',
                    }
              }
            />
            {cooldownActive ? (
              <p className="pb-6 text-center text-xs text-[var(--ink-mut)]">
                Analysis queued — check back in a few minutes.
              </p>
            ) : null}
          </Card>
        ) : (
          <div className="space-y-4">
            <div className="flex flex-wrap items-center justify-between gap-3">
              <div className="eyebrow">Latest analysis</div>
              <Button
                size="sm"
                variant="ghost"
                icon={<Sparkles size={14} aria-hidden />}
                loading={trigger.isPending}
                disabled={cooldownActive || trigger.isPending}
                onClick={runTrigger}
                data-testid="insights-trigger-btn"
              >
                Run analysis now
              </Button>
            </div>

            {est?.usdValue !== undefined ? (
              <>
                <Stat
                  label="Est. downgradable spend"
                  value={usd(est.usdValue)}
                  testId="insights-est-savings-stat"
                />
                <div className="rounded-[var(--radius-btn)] border border-[var(--line)] bg-[var(--paper)] p-3 text-xs leading-relaxed text-[var(--ink-mut)]">
                  {METHODOLOGY_DISCLOSURE}
                </div>
              </>
            ) : null}

            <Card>
              <p className="text-sm text-[var(--ink-mut)]">
                {periodLabel} · generated {absTime(insight.generated_at)}
              </p>

              {restEntries.length > 0 ? (
                <dl className="mt-4 grid grid-cols-2 gap-x-6 gap-y-2 border-t border-[var(--line)] pt-4">
                  {restEntries.map(([key, value]) => (
                    <div key={key} className="contents">
                      <dt className="text-sm text-[var(--ink-mut)]">{humanizeKey(key)}</dt>
                      <dd className="num text-right text-sm">{formatSummaryValue(value)}</dd>
                    </div>
                  ))}
                </dl>
              ) : null}

              <details className="mt-4">
                <summary className="focus-ring cursor-pointer select-none text-xs font-medium text-[var(--ink-mut)] hover:text-[var(--ink)]">
                  Full detail
                </summary>
                <div className="mt-2">
                  <CodeBlock
                    code={JSON.stringify(insight.detail, null, 2)}
                    testId="insights-detail-copy"
                  />
                </div>
              </details>
            </Card>
          </div>
        )}
      </PlanGate>
    </div>
  );
}
